collector:
  enabled: true
  config: |
    exporters:
      otlp:
        endpoint: signoz-otel-collector.platform.svc.cluster.local:4317
        tls:
          insecure: true
    extensions:
      health_check: {}
    processors:
      batch: {}
      k8sattributes:
        auth_type: serviceAccount
        extract:
          metadata:
          - k8s.pod.name
          - k8s.namespace.name
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.name
          - from: resource_attribute
            name: k8s.namespace.name
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    service:
      extensions:
      - health_check
      pipelines:
        traces:
          exporters:
          - otlp
          processors:
          - k8sattributes
          - batch
          receivers:
          - opencensus
          - otlp

jaeger:
  enabled: false

webhook:
  collectorSvcAddr: collector.linkerd-jaeger:4317
  collectorTraceProtocol: opentelemetry
  collectorSvcAccount: collector