# SigNoz Helm values
global:
  storageClass: "do-block-storage"

clickhouse:
  enabled: true
  persistence:
    enabled: true
    size: 20Gi
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi" 
      cpu: "1000m"

query-service:
  enabled: true
  image:
    repository: signoz/query-service
    tag: 0.43.0
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

frontend:
  enabled: true
  image:
    repository: signoz/frontend
    tag: 0.43.0
  service:
    type: LoadBalancer
    port: 3301
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"

otel-collector:
  enabled: true
  image:
    repository: signoz/signoz-otel-collector
    tag: 0.88.11
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  config:
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'linkerd-controller'
            kubernetes_sd_configs:
            - role: pod
              namespaces:
                names: ['linkerd']
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_container_name]
              action: keep
              regex: ^prometheus$
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: ^admin-http$
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: __address__
              replacement: linkerd-controller-api.linkerd.svc.cluster.local:8085
          - job_name: 'linkerd-service-mirror'
            kubernetes_sd_configs:
            - role: pod
              namespaces:
                names: ['linkerd']
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_linkerd_io_control_plane_component]
              action: keep
              regex: linkerd-service-mirror
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: ^admin-http$
          - job_name: 'linkerd-proxy'
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - source_labels: [__meta_kubernetes_pod_container_name]
              action: keep
              regex: ^linkerd-proxy$
            - source_labels: [__meta_kubernetes_pod_container_port_name]
              action: keep
              regex: ^linkerd-admin$
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: pod
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: namespace
          - job_name: 'linkerd-prometheus'
            static_configs:
            - targets: ['prometheus.linkerd-viz.svc.cluster.local:9090']

otel-collector-metrics:
  enabled: true
  image:
    repository: signoz/signoz-otel-collector
    tag: 0.88.11
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

alertmanager:
  enabled: true
  image:
    repository: signoz/alertmanager
    tag: 0.23.4