apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: grpc-tracing
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: jaeger
    randomSamplingPercentage: 100.0
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: REQUEST_COUNT
      tagOverrides:
        grpc_response_status:
          value: response.grpc_status | "unknown"
        method:
          value: request.method | request.grpc_method | "unknown"