apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product-service
  labels:
    app: product-service
    service: product
spec:
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
    name: grpc
  selector:
    app: product-service
  type: ClusterIP